### ISSUE TITLE
doesn't support latest react version yet?

### ISSUE THREAD

**Issue by mouthzipper** [leoasis/react-sound#1]
npm ERR! peerinvalid The package react@0.14.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-sound@0.2.1 wants react@^0.13.3

**Comment by leoasis** [comment]
Yeah, haven't added support for it yet. Will do that sometime this next week! Or you can send a PR if you want :)

**Comment by leoasis** [comment]
@mouthzipper the new version 0.3.0 has been published with support for react 0.14. Let me know how that goes! Closing. If something doesn't work (related to the react version), you can reopen
