### ISSUE TITLE
where should the sound file exist?

### ISSUE THREAD

**Issue by pcompassion** [leoasis/react-sound#19]
I'm trying to set url for server as I do with ajax . eg) /foo/bar.html

But it doesn't seem to work.

**Comment by leoasis** [comment]
The url is just delegated to the [SoundManager2](http://www.schillmania.com/projects/soundmanager2/) object. It should be a url to a sound file of a supported format. Please read the docs there and make sure the url you're passing works directly with the soundmanager library directly.

**Comment by leoasis** [comment]
Hope this answered your question! If not, feel free to reopen
