### ISSUE TITLE
Updating with status PLAYING when previous status is PLAYING

### ISSUE THREAD

**Issue by veob** [leoasis/react-sound#2]
Hello @leoasis,
Updating component with status PLAYING when previous status also is PLAYING causes no playing at all. 
Problem with [this](https://github.com/leoasis/react-sound/blob/master/src/index.js#L71) condition:

``` javascript
     if (this.props.playStatus === playStatuses.PLAYING) {
        if (prevProps.playStatus === playStatuses.STOPPED) {
          sound.play();
        } else if (prevProps.playStatus === playStatuses.PAUSED) {
          sound.resume();
        }
         //if prevProps.playStatus is PLAYING nothing happens...
    }
```

Is this right behavior? If not, I can make a PR to fix this.

**Comment by leoasis** [comment]
What is the behavior your are trying to achieve? If it's playing then it should keep playing. Are you talking about the case when the song finished?

**Comment by veob** [comment]
I was talking about the case when I click on the next song in the playlist. I was doing it without changing the state from PLAYING. 

But I think I get it now. I should change status to STOPPED before changing to the next song, right?

**Comment by leoasis** [comment]
Ahh I think you're right, we're not checking if the url of the song changed and play the new sound again. We should probably check the `sound` instance for its status instead of relying on the previous prop being STOPPED. We can use the `playState` property of the sound, and probably the `paused` property

**Comment by leoasis** [comment]
So something like this, more or less:

``` js
if (this.props.playStatus === playStatuses.PLAYING) {
        if (sound.playState === 0) {
          sound.play();
        } else if (sound.paused) {
          sound.resume();
        }
    }
```

**Comment by veob** [comment]
Well, this looks good. 
Previously I had to stop playing programmatically and only then I could change the track:

``` javascript
this.replaceState({playing: Sound.status.STOPPED}, () => {
    this.setState({
        currentTrack: currentTrack,
        playing: Sound.status.PLAYING
    });
});
```

With your proposed patch I can change current track without worrying about the status.

Should I make the PR?

**Comment by leoasis** [comment]
Yeah! I think having to go to stopped and then back to playing again is an imperative action in disguise, it's not declarative. The component should be able to notice that the sound url changed and if it is still playing, start playing the sound.

**Comment by leoasis** [comment]
A new version with a fix for this issue is released! https://github.com/leoasis/react-sound/releases/tag/v0.4.0
