### ISSUE TITLE
how to preload mp3 so its ready to be played on user click?

### ISSUE THREAD

**Issue by jasan-s** [leoasis/react-sound#20]
there is a lag on mobile devices , on desktop the audio plays without any noticeable lag.

**Comment by leoasis** [comment]
As soon as you mount the `Sound` component with a url, the sound will start loading (you can track the `loading` state with the `onLoading` callback prop). What you can do is render the sound but still not play it, and only show the player controls when the sound is sufficiently loaded.

Does that help?

**Comment by leoasis** [comment]
Hope this helped you! If not, you can reopen this and we can keep discussing

**Comment by rshkv** [comment]
I'm mounting the component with `url` and `playStatus` `STOPPED` and there is no loading as I can tell from the SoundManager logs. Only once I change to`PLAYING`, the SoundManager starts to log _"progress, x% loaded"_.

I will try a work around using `onLoading`.

**Comment by heks** [comment]
I am experiencing the same thing as @rshkv, is there a fix for this ? How are you doing your work around with `onLoading` @rshkv  ?

**Comment by rshkv** [comment]
@heks, sorry for the late response.

For my workaround I'm mounting the component with playStatus `PLAYING` and keep it playing until it's loaded. You can also check out [the code](https://github.com/rshkv/spotplot/blob/master/client/src/components/Player.jsx).

**Comment by mtuchi** [comment]
Sorry anyone with a work around for this ?
