### ISSUE TITLE
Playback from Readable

### ISSUE THREAD

**Issue by nukeop** [leoasis/react-sound#23]
Hi

I'm using this module in my music player to great effect, really fantastic component.

I was wondering how hard would it be to add support for streaming from Readable streams instead of urls? I want to stream from a website that only returns an audio file if a particular header is passed, but I can't pass this header to react-sound, so I open the stream myself and would like to play that stream. The only solution for now is saving the stream locally in a temporary file and passing that to react-sound which is far from ideal.

Is it possible to add support for Readable streams?

Thanks

**Comment by leoasis** [comment]
Hi! Glad that you are found this component useful! Happy to hear that.

Regarding adding support for Readable streams, this component uses soundmanager2 under the hood, which is meant for client side sound management. In the client AFAIK there are no readable streams, that's a node concept. So I'm not sure how that would be possible to do at all. Anyway, I checked [soundmanger2's documentation](http://www.schillmania.com/projects/soundmanager2/doc/) and I couldn't find anything related to being able to pass streams to it, only urls.

Maybe I could understand the use case better with an example?

**Comment by nukeop** [comment]
Yeah, you're correct, looks like soundmanager won't be able to handle this.

Here's an example:
http://mp3monkey.net/audio/998c1ce908e9a82a5b45d06360c575ae/38a4b18c7a50cf456da47a29c739cff2/Death_Grips_-No_Love_.mp3

You can access this mp3 if you pass the referer, but if you don't, it redirects to generic hotlink protection screen.

**Comment by leoasis** [comment]
Maybe you can stream that yourself in your node server? That is, make the request from the server and stream that mp3 back to the client. So that the client doesn't need to send that header

**Comment by nukeop** [comment]
Hm, not really, since I'm developing for Electron. That's why I wanted to play from a stream, because it's the server that's supposed to do it here.

**Comment by leoasis** [comment]
I'm afraid you won't be able to make that work unless you fetch the url manually using a server that proxies the audio and passes that header. SoundManager2 is using the HtmlAudioElement (https://developer.mozilla.org/en/docs/Web/API/HTMLAudioElement) under the hood and that doesn't allow to pass custom headers to the request (as with img tags, for example).

**Comment by leoasis** [comment]
Closing since this is not supported by soundmanager and it's not a goal of this lib to add support if it requires significant effort to do it. Feel free to reopen if you found another way to make it work or if it will be supported by soundmanager.
