### ISSUE TITLE
Volume Fade In/Out on the start&end of playing

### ISSUE THREAD

**Issue by Dachang** [leoasis/react-sound#25]
Is it possible to create a method to fade in/out the volume when start playing, as well as stop/pausing the audio clip? 
Many thanks!

**Comment by leoasis** [comment]
There's nothing built-in for that, but you should be able to do that by controlling the `volume` prop via a `state` field, and in a `setInterval` you can start decreasing that volume via `this.setState({ volume: volume - someDelta })` until you reach 0, in which case you stop the sound directly.

If you want to do cross fading with another sound, you can render two sounds and do the opposite with the other one, increasing the volume.

Hope this helps!

**Comment by Dachang** [comment]
Exactly. Thanks for the reply!

**Comment by leoasis** [comment]
Awesome, feel free to close this issue if that helped!
