### ISSUE TITLE
Weird behavior on url state change

### ISSUE THREAD

**Issue by christiannwamba** [leoasis/react-sound#3]
Hi

While a sound plays and the `url` of `Sound` property is changed by updating states, the audio stops and doesn't play anymore. Any workaround for this?

An example is updating the `url` using a html text box while the sound is playing.

**Comment by leoasis** [comment]
Interesting, thanks for filing the issue! I was able to reproduce in the examples. Will fix!

**Comment by leoasis** [comment]
Fixed in the latest release https://github.com/leoasis/react-sound/releases/tag/v0.4.0
