### ISSUE TITLE
Support for looping

### ISSUE THREAD

**Issue by philliplongman** [leoasis/react-sound#36]
A "looping" status would be nice. Right now, to loop, I have to make React re-render the component over and over again. It seems more complicated than necessary.

**Comment by leoasis** [comment]
Hey! Yeah I think you're right. We could have a `loop` prop that when set to `true`, would make the song keep playing until you change the play status, starting over if needed. Wanna send a PR?

**Comment by leoasis** [comment]
This was already added!
