### ISSUE TITLE
OnLoaded callback

### ISSUE THREAD

**Issue by tulsileathers** [leoasis/react-sound#40]
I have a use for a callback that fires once after the stream is successfully loaded right before it begins to play. Would you accept a PR with this callback added as a prop?

**Comment by tulsileathers** [comment]
Soundmanager2 has this callback. It's called onload. http://www.schillmania.com/projects/soundmanager2/demo/api/#create-with-onload

**Comment by leoasis** [comment]
Yeah that callback is missing in the component, want to contribute and add it?

**Comment by tulsileathers** [comment]
PR incoming
