### ISSUE TITLE
Why the console.log?

### ISSUE THREAD

**Issue by cbroberg** [leoasis/react-sound#42]
How do you turn it off? 

SoundManager V2.97a.20170601 (HTML5-only mode)
soundmanager2.js:1305 SoundManager 2 HTML5 support: mp3 = true, mp4 = true, ogg = true, opus = true, wav = true, flac = true
soundmanager2.js:1305 SoundManager 2: Ready. ✓
soundmanager2.js:1305 soundManager.createSound(): sound0 (https://raw.githubusercontent.com/scottschiller/SoundManager2/master/demo/_mp3/click-high.mp3)
soundmanager2.js:1303 sound0: Merged options: {url: "https://raw.githubusercontent.com/scottschiller/SoundManager2/master/demo/_mp3/click-high.mp3", autoLoad: true, volume: 100, position: 0, whileloading: ƒ, …}
soundmanager2.js:1307 sound0: load (https://raw.githubusercontent.com/scottschiller/SoundManager2/master/demo/_mp3/click-high.mp3)
soundmanager2.js:1307 sound0: load (https://raw.githubusercontent.com/scottschiller/SoundManager2/master/demo/_mp3/click-high.mp3)

**Comment by eveningkid** [comment]
Hi,

I actually suggested [a pull request](https://github.com/leoasis/react-sound/pull/29) back in time about this. 

You need to tweak a little something at the `sound-manager` package level.
[The following line](https://github.com/leoasis/react-sound/pull/29/commits/0af89c271a862c90c547b006004f163a2f87ea5a#diff-1fdf421c05c1140f6d71444ea2b27638R175) might help you.

**Comment by leoasis** [comment]
Fixed in v1.0.0 https://github.com/leoasis/react-sound/releases/tag/v1.0.0

**Comment by subalee** [comment]
@leoasis Unfortunately, with using create-react-app I'm unable to turn the debugging off. The only option for me would be to eject the app and create and [alias](https://github.com/leoasis/react-sound/issues/13#issuecomment-240620043).

**Comment by leoasis** [comment]
Yes, the changes in v1.0.0 only removed the debugging in production. If you want to remove it in development, then you should alias it, or you can also set the debugMode to false http://www.schillmania.com/projects/soundmanager2/doc/#soundmanager-debugmode
