### ISSUE TITLE
need help to use react-sound library 

### ISSUE THREAD

**Issue by sdeseille** [leoasis/react-sound#43]
Hello

I don't know if this is the right place to ask that but i tried to use react-sound in order to play an audio file generated from a node server but that don't work. I can see following error message from react log 

soundManager.createSound(): sound0 (../audio/res2.wav)
soundmanager2.js:1303 sound0: Merged options: {url: "../audio/res2.wav", autoLoad: false, volume: 100, position: 0, whileloading: ƒ, …}
soundmanager2.js:1307 sound0: play(): Attempting to load
soundmanager2.js:1307 sound0: load (../audio/res2.wav)
soundmanager2.js:1307 sound0: waiting
soundmanager2.js:1307 sound0: loadstart
:3000/audio/res2.wav:1 GET http://localhost:3000/audio/res2.wav net::ERR_ABORTED
soundmanager2.js:1307 sound0: suspend
soundmanager2.js:1307 sound0: HTML5 error, code 4 (MEDIA_ERR_SRC_NOT_SUPPORTED)
soundmanager2.js:1305 sound0: Failed to load / invalid sound? Zero-length duration reported. (../audio/res2.wav)
SoundManager._writeDebug @ soundmanager2.js:1305
SMSound._onload @ soundmanager2.js:3219
(anonymous) @ soundmanager2.js:3994
(anonymous) @ soundmanager2.js:3885
localhost/:1 Uncaught (in promise) DOMException: Failed to load because no supported source was found.
Promise (async)
SMSound.play @ soundmanager2.js:2129
(anonymous) @ index.js:85
(anonymous) @ index.js:183
_createSound @ index.js:41
createSound @ index.js:158
componentDidMount @ index.js:83
(anonymous) @ ReactCompositeComponent.js:265
measureLifeCyclePerf @ ReactCompositeComponent.js:75
(anonymous) @ ReactCompositeComponent.js:264
notifyAll @ CallbackQueue.js:76
close @ ReactReconcileTransaction.js:80
closeAll @ Transaction.js:206
perform @ Transaction.js:153
perform @ Transaction.js:140
perform @ ReactUpdates.js:89
flushBatchedUpdates @ ReactUpdates.js:172
closeAll @ Transaction.js:206
perform @ Transaction.js:153
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
enqueueUpdate @ ReactUpdates.js:200
enqueueUpdate @ ReactUpdateQueue.js:24
enqueueSetState @ ReactUpdateQueue.js:219
ReactComponent.setState @ ReactComponent.js:63
(anonymous) @ App.js:1058
Promise resolved (async)
sendMessage @ App.js:1056
onInputKeyUp @ App.js:1042
onKeyUp @ App.js:992
ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js:69
executeDispatch @ EventPluginUtils.js:85
executeDispatchesInOrder @ EventPluginUtils.js:108
executeDispatchesAndRelease @ EventPluginHub.js:43
executeDispatchesAndReleaseTopLevel @ EventPluginHub.js:54
forEachAccumulated @ forEachAccumulated.js:24
processEventQueue @ EventPluginHub.js:257
runEventQueueInBatch @ ReactEventEmitterMixin.js:17
handleTopLevel @ ReactEventEmitterMixin.js:28
handleTopLevelImpl @ ReactEventListener.js:72
perform @ Transaction.js:140
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:97
dispatchEvent @ ReactEventListener.js:147 

Can you help me to understant what i'm missing ?

regards

sdeseille

**Comment by ghost** [comment]
Your error message says that no supported source was found. Try just putting in the file name into the url property.

e.g. `url="filename.wav"`

**Comment by karla-moreno** [comment]
I did the above, also had to add the files to the 'public' folder :)

**Comment by sdeseille** [comment]
Ok thanks, i will try that.
