### ISSUE TITLE
Sound starts playing from the beginning on parent update

### ISSUE THREAD

**Issue by Fxlr8** [leoasis/react-sound#45]
I am making a notifications component and I want to play a short sound when the notification appears. Every notification component contains `Sound` component inside with play status set to playing.
```
<Wrapper>
    <Notification/>
    <Notification/>
    <Notification/>
</Wrapper>
```

**expected behavior:**
when notification is added, the sound is rendered, played to the end and stopped

**real behavior:**
the sound is played not only when notification is rendered, but also every time parent component is updated. Ex: another notification is removed or added.

How can I implement the "play once and shut up" behavior here? I don't want to move sound handling to the parent component because I want the sounds to overlap when a bunch of notifications appears in a short period of time. Thanks in advance

**Comment by karla-moreno** [comment]
@Fxlr8 could you provide a snippet of your code? I experienced a similar issue and I think I can help. I fixed it by adding a 'handleClick' function so sounds only play when the button is clicked, something similar could be useful like a 'handleNewNotification' function

**Comment by leoasis** [comment]
I think the problem here could be related to how you're setting up the `key`s in the list of `<Notification />`s. Make sure you're using unique values that represent the same object between renders, otherwise the components may be unmounted and remounted, causing the sound to play again.

**Comment by leoasis** [comment]
Closing this due to lack of follow up. Feel free to reopen if you have more info!

**Comment by Fxlr8** [comment]
@leoasis, sorry, there really was a problem with missing `key` attribute.
