### ISSUE TITLE
Multiple sound components

### ISSUE THREAD

**Issue by RubyEDE** [leoasis/react-sound#47]
How can I get multiple sound components to work?

**Comment by leoasis** [comment]
What do you mean exactly? You can render multiple components and you should be able to listen to all at the same time.

**Comment by karla-moreno** [comment]
@CaptainBoy can you provide a snippet of your code?

@leoasis I actually experienced an issue where that's not the case from iOS safari! Not sure if it's specific to the package/sound-manager

**Comment by leoasis** [comment]
@deathnaut have you seen the note below the example in this section of the readme https://github.com/leoasis/react-sound#how-to-use? SoundManager by default restricts the amount of sounds to be played at the same time in mobile devices

**Comment by karla-moreno** [comment]
@leoasis I actually saw that in the sound manager library docs a while after I'd commented that lol will definitely look into integrating it later though

**Comment by leoasis** [comment]
Closing since it looks like that solved your issue. Fee free to reopen otherwise, and provide more info.
