### ISSUE TITLE
peerDependencies doesn't allow release versions of React 16

### ISSUE THREAD

**Issue by koss-lebedev** [leoasis/react-sound#57]
Hey Leonardo,

peerDependencies for React is specified as `^16.0.0-0`, so it only allows pre-release versions. Can we change that?

Thanks!

**Comment by leoasis** [comment]
Hey @koss-lebedev! Sorry for taking to long to answer here. Are you sure about this? I'm not having any issues with the version range specified and using, say, react 16.2.0. Do you have a particular example that's not working so we can take a look at?
