### ISSUE TITLE
Provide Option to Turn On or Off console log

### ISSUE THREAD

**Issue by bergkampho** [leoasis/react-sound#8]
Can I turn off the console log of soundManager?

**Comment by leoasis** [comment]
This is something you can set up to the global sound manager object http://www.schillmania.com/projects/soundmanager2/doc/#sm-config. `react-sound` doesn't do any prior setup of it

**Comment by bergkampho** [comment]
@leoasis: Other than using the global sound manager object for the debug option, can i choose to import soundmanager2-nodebug-jsmin.js instead of soundmanager2.js ?

**Comment by leoasis** [comment]
Oh that's interesting, seems there's no way to strip debug code like with React using something like webpack with `DefinePlugin`. How are you using `react-sound`? Are you using a bundler like webpack or browserify? If so, you can alias soundmanager2 to point to the nodebug version when bundling for prod, and keep it as is for dev.

**Comment by bergkampho** [comment]
Yes, it works fine. I'm using webpack with `alias` to point to the nodebug version. Thanks.

**Comment by leoasis** [comment]
Cool! You're welcome!
