### ISSUE TITLE
Could not resolve dependency issue for newer react@ ^17 

### ISSUE THREAD

**Issue by ridhwaans** [leoasis/react-sound#98]
```
 Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.3.0 || ^16.0.0-0" from react-sound@1.2.0
npm ERR! node_modules/react-sound
npm ERR!   react-sound@"^1.2.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
perhaps add support for the latest react versions

**Comment by juxuny** [comment]
It's also could not resolve dependicy issue for react@18
> Could not resolve dependency:
npm ERR! react-sound@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@"^15.3.0 || ^16.0.0-0" from react-sound@1.2.0
npm ERR!   node_modules/react-sound
npm ERR!     react-sound@"*" from the root project
